package model;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Training generated by hbm2java
 */
@Entity
@Table(name = "Training", catalog = "SP2Team08")
public class Training implements java.io.Serializable {

	private Integer idTraining;
	private int adres;
	private int leerkracht;
	private String trainingNaam;
	private Set<TrainingDetail> trainingDetails = new HashSet<TrainingDetail>(0);

	public Training() {
	}

	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTraining", unique = true, nullable = false)
	public Integer getIdTraining() {
		return this.idTraining;
	}

	public void setIdTraining(Integer idTraining) {
		this.idTraining = idTraining;
	}


	@Column(name = "idAdres", nullable = false)
	public int getAdres() {
		return this.adres;
	}

	public void setAdres(int adres) {
		this.adres = adres;
	}

	@Column(name = "idLeerkracht", nullable = false)
	public int getLeerkracht() {
		return this.leerkracht;
	}

	public void setLeerkracht(int leerkracht) {
		this.leerkracht = leerkracht;
	}

	@Column(name = "trainingNaam", nullable = false, length = 30)
	public String getTrainingNaam() {
		return this.trainingNaam;
	}

	public void setTrainingNaam(String trainingNaam) {
		this.trainingNaam = trainingNaam;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "training")
	public Set<TrainingDetail> getTrainingDetails() {
		return this.trainingDetails;
	}

	public void setTrainingDetails(Set<TrainingDetail> trainingDetails) {
		this.trainingDetails = trainingDetails;
	}

}
